version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "14:00"
      timezone: America/Denver
    open-pull-requests-limit: 5
    groups:
      rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "14:30"
      timezone: America/Denver
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
